# Site settings
title: CyberGuardians
description: Cybersecurity education resources
baseurl: "" # the subpath of your site, e.g. /BruteForceDemo
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Include/exclude files
include:
  - _includes
  - _layouts
